<?php
/**
 * Author: David<yiwei.duan@meta-insight.com>
 * Date: 2018/8/21
 * Time: 10:52
 */

namespace frontend\modules\dev\controllers\website;

use common\models\User;
use yii\base\Controller;
use yii\base\Event;


/**
 * Class HelloController
 * == hello
 *
 * @package frontend\modules\dev\controllers\website
 */
class HelloController extends Controller
{
    public function test(...$args){
        var_dump($args);
    }

    public function testOne(){
        $user=new User();
        $user->on('dsa', function ($event) {
            echo 'Hello';
        });
        $user->on('dsa', function ($event) {
            echo 'World';
        });
        $user->trigger('dsa');
//        \Yii::$app->on('bar', function ($event) {
//            echo get_class($event->sender);        // 显示当前触发事件的对象的类名称
//        });
//
//        \Yii::$app->trigger('bar', new Event(['sender' => $this]));
    }

    public function actionOne()
    {
        $this->testOne();
        exit();
        $this->test('dsa','gfd',1,['fds','gfdh']);
        exit();
        $x = true and false;
        $x = $x = 3 + intval("15%") + intval("$25");
        $text = 'John ';
        $text[10] = 'Doe';
        $text[11] = 'jhge';
        $x = NULL;

        if ('0xFF' == 255) {
            $x = (int)'0xFF';
        }
//        return $x;
        var_dump($x);
    }

    public function actionSix()
    {
        phpinfo();
    }

    public function afterAction($action, $result)
    {
//        var_dump($result.'dsada');
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}